language: c
sudo: required
before_install:
  - sudo ./install-pgi.sh --nvidia --managed --mpi --mpi-gpu
  - export PATH=$PATH:$PGI_BIN_DIR
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PGI_LIB_DIR
  - export MANPATH=$MANPATH:$PGI_MAN_PATH
script:
  - pgcc -dM -E /dev/null
notifications:
  email:
    on_success: never
    on_failure: never
