language: c
sudo: required
before_install:
  - sudo ./install-pgi.sh --nvidia --managed --mpi --mpi-gpu
  - export PGI_HOME=/usr/local/pgi/linux86-64/17.4
  - export PATH=$PATH:$PGI_HOME/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PGI_HOME/lib
  - export MANPATH=$MANPATH:$PGI_HOME/man
script:
  - pgcc -dM -E /dev/null
notifications:
  email:
    on_success: never
    on_failure: never
